=== PoESkillTree/PoESkillTree/UnitTests/TestBuilds/BuildUrls.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <!-- bandit - enumerable type -->
  <xs:simpleType name="bandit">
    <xs:restriction base="xs:string">
      <!-- None = 0 (poeplanner) -->
      <xs:enumeration value="None"/>
      <!-- Alira = 1 (poeplanner) -->
      <xs:enumeration value="Alira">
        <xs:annotation>
          <xs:documentation>
            +60 Mana (Normal); +5% Cast Speed (Cruel); +1 Power Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <!-- Oak = 2 (poeplanner - 3) -->
      <xs:enumeration value="Oak">
        <xs:annotation>
          <xs:documentation>
            +60 Life (Normal); +16% Physical Damage (Cruel); +1 Endurance Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <!-- Kraityn = 3 (poeplanner - 2) -->
      <xs:enumeration value="Kraityn">
        <xs:annotation>
          <xs:documentation>
            +10 all Res (Normal); +8% Attack Speed (Cruel); +1 Frenzy Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <!-- url - anyURI type extended with 'name' and 'value' attributes -->
  <xs:complexType name="url">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- urls - contains default (primary) Url and optional alternative Urls -->
  <xs:element name="urls">
    <xs:annotation>
      <xs:documentation>
        Contains single default Url and multiple optional alternative Urls.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="default" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="alternative" type="url" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueUrlName">
      <xs:selector xpath="alternative"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueUrl">
      <xs:selector xpath=".//*"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>

  <!-- bandits - tag, containing bandits selection -->
  <xs:element name="bandits">
    <xs:complexType>
      <xs:attribute name="normal" type="bandit" />
      <xs:attribute name="cruel" type="bandit"/>
      <xs:attribute name="merciless" type="bandit"/>
    </xs:complexType>
  </xs:element>

  <!-- document schema -->
  <xs:element name="testData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="builds" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="build" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element ref="urls"/>
                    <xs:element name="description" type="xs:token" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="tags" type="xs:string" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>
                          Contains multiple tokens, separated by a semicolon.
                          Tags can be used to find associated builds.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element ref="bandits" minOccurs="0" maxOccurs="1"/>
                  </xs:all>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="nodes" type="xs:integer"/>
                  <xs:attribute name="treeVersion" type="xs:integer"/>
                  <xs:attribute name="characterClassId" type="xs:byte"/>
                  <xs:attribute name="ascendancyClassId" type="xs:byte"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="uniqueBuildName">
            <xs:selector xpath="build"/>
            <xs:field xpath="@name"/>
          </xs:unique>
          <xs:unique name="uniqueBuildUrl">
            <xs:selector xpath="build/urls"/>
            <xs:field xpath="default"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PoESkillTree/PoESkillTree/UnitTests/TestBuilds/BuildUrls.xml
<?xml version="1.0" encoding="utf-8" ?>
<testData
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="BuildUrls.xsd">
  <builds>
    <build name="PoeplannerWitchOccultistAscendant" treeVersion="4" characterClassId="3" ascendancyClassId="1" points="113" ascendancyPoints="8">
      <urls>
        <default>http://poeplanner.com/AAQAAPcTEAB534rpAkuuGyXZW20ZEVA1uacrHU-X9FJTPV-XlUyz0B_v6yBuUDARD6yY99eESFxrw23i9wFvi3oi9GwLkyd_xsHF7Bgsv4_60NBfakcG2-e0xcM6KjhcQFS9Fe2Wi9W5h8unm3WezxXYdrk-rGYs4X3j8uFjQ2wI8YrviPk3189Jsb6KoS8RlpAbcFaaE9vUieDmWJMfSRPK07QM6roNfBXXhq5WYw5IXfIqC3BSoqMPxDt8uMrw1UlROw32_Kc0YqxsjJ2qES_rY7VI1EKEb3X9Fr8PqySLNj1W9dtul9COihpI9Ch88JEHu_wVfn6hadgAAAAAAA==</default>
        <alternative name="pathofexile">https://pathofexile.com/fullscreen-passive-skill-tree/AAAABAMBAQFvDXwOSA-rD8QRDxEvEVARlhV-FdcV7Ra_GkgbJR1PIG4i9CSLKgsqOCy_LOE1uTY9Ow07fD1fRwZJE0lRSbFLrkyzUDBSU1S9VmNW9VxAXGtd8l9qYqxjQ2nYbAhsC2yMbRlwUnBWdZ51_XzwfeN-oX_GhEiEb4auh8uJ4It6joqP-pAbkQeTH5MnlouXlZfQl_SaE52qoS-io6crpzSnm6xmrJi0DLTFtUi4yrk-u_y-isHFwzrDbcrTzxXQH9DQ1ELVudfP2HbZW9tu29Tb59-K4vfmWOkC6rrrY-wY74jv6_DV8Yry4fQo9vz31_k3</alternative>
        <alternative name="pathofexileWindowed">https://pathofexile.com/passive-skill-tree/AAAABAMBAAFvDXwOSA-rD8QRDxEvEVARlhV-FdcV7Ra_GkgbJR1PIG4i9CSLKgsqOCy_LOE1uTY9Ow07fD1fRwZJE0lRSbFLrkyzUDBSU1S9VmNW9VxAXGtd8l9qYqxjQ2nYbAhsC2yMbRlwUnBWdZ51_XzwfeN-oX_GhEiEb4auh8uJ4It6joqP-pAbkQeTH5MnlouXlZfQl_SaE52qoS-io6crpzSnm6xmrJi0DLTFtUi4yrk-u_y-isHFwzrDbcrTzxXQH9DQ1ELVudfP2HbZW9tu29Tb59-K4vfmWOkC6rrrY-wY74jv6_DV8Yry4fQo9vz31_k3</alternative>
        <alternative name="tinyurl">http://tinyurl.com/glcmaeo</alternative>
        <alternative name="poeurl">http://poeurl.com/0dE</alternative>
        <alternative name="poeurlRedirect">http://poeurl.com/redirect.php?url=0dE</alternative>
        <alternative name="poeurlNoProto">www.poeurl.com/0dE</alternative>
        <alternative name="poeurlNoPrefix">poeurl.com/0dE</alternative>
        <alternative name="doubleShortened">https://goo.gl/kKjcuK</alternative>
      </urls>
      <description>
        Original build from the issue #427.
        The build is valid and contains only nodes information (no equip or auras).
      </description>
      <bandits merciless="Alira"/>
      <tags>#427; bandits</tags>
    </build>
    <build name="PoeplannerWitchOccultist" treeVersion="4" characterClassId="3" ascendancyClassId="1" points="113" ascendancyPoints="0">
      <urls>
        <default>https://pathofexile.com/passive-skill-tree/AAAABAMBAAFvDXwOSA-rD8QRDxEvEVARlhXXFe0WvxslHU8gbiL0JIsqCyo4LL8s4TW5Nj07DTt8PV9HBkkTSVFJsUuuTLNQMFJTVL1WY1b1XEBca13yX2pirGNDbAhsC2yMbRlwUnBWdZ51_X3jf8aESIRvhq6Hy4ngi3qOio_6kBuTH5MnlouXlZfQl_SaE52qoS-io6crpzSnm6xmrJi0DLTFtUi4yrk-vorBxcM6w23K088V0B_Q0NRC1bnXz9h22VvbbtvU2-ffiuL35ljpAuq662PsGO-I7-vw1fGK8uH2_PfX-Tc=</default>
      </urls>
      <description>
        Original build from the issue #427.
        The build is valid and contains only nodes information (no equip or auras).
      </description>
      <bandits merciless="Alira"/>
      <tags>#427; bandits; test</tags>
    </build>
    <build name="PoeplannerFullTreeWithMaxScionAndBandits" treeVersion="4" characterClassId="0" ascendancyClassId="1" points="1368" ascendancyPoints="30">
      <urls>
        <default>http://poeplanner.com/AAQACv0QOQV8AAYAXgDuAQkBbwGRAbwB0QHcAecCEQLQAuMDAAMeAycDdQOHA5YD7gQHBIcEsQSzBOQFLQU8BUIFZgV9BZMFtQX5Bg4GIAYjBjkGSQZwBncGoAaiBx4HYwd1B6UILghJCGcIiQixCNQI9AkzCVgJlgmgCaoJuwn2CpsLYQvBDF8McwzyDPcNHw18DY0NzQ3RDjwOSA5cDo4Pqw_EEFgQexCXEMwQ8BEPERoRLREvEVARgRGWEcIR1RJpEuETTBNQE2wTbRNxE4MTyRPMFAkUIBRNFHEUdRSOFKkUsBT2FSAVUBW4FdcV5xXsFe0V8BX2Ff0WQBZvFqoWvxbzFxwXLxc-F1QX3BfhGDwYVhhdGGUYahiRGNcY2xkuGYYZihmOGbQZ1xnpGf4aOBo-GlUabBqBGo0ajxrkGwEbJRtFG5cbqhutG8gb4BvxG_ocpxzOHNwc5x0UHU8dgx2qHb4d2R6UHt8e8B8CHxgfQR9bH8cgbiCcITQhVSFgIXYhsCHAIcMiJiKBIq8i4iLqIvQjMSNfI9Mj9iSLJJsknSSqJLAk2CT9JSclPyW8Jd8mPCaIJpUm-CcLJyAnIScvJ6kn7SgqKPopLilPKaUqCyoTKjgqTSpTKlsqjSqYKworUCt4K7YsRiyFLJwspiynLL8s4SzpLPstHy0wLVUtfS2DLYstqC3SLgguIy5TLpQvby-dL8wwWzBxMHcwfDCXMZ4xsDGzMfox-zIBMgkyGDI0Mk4yfjKJMpQy0TN4M4czkjQKNCA0MTSONPc1kjW5NdY17zY9Nok2xTbYNug26TdHN2Y3gTeDN9Q4UziWOQ45UjmKOdQ53TpCOlI6WDqdOq06szrYOuE67TsNOyg7Ozt8O-M8BTwoPC08vTzvPQ89Pj1fPdE93T3iPfw-zz8nP3M__ECgQT9BckF0QYdBlkJLQo5DE0MxQzZDVENjQ8hD50QERA1EikSeRKFEq0TSRPtFCkVHRXxFfkWORZZFnUWpRblF9EZpRnFGt0bXRwZHfke3R-JIeEjnSO5JD0kTSRtJUUmxSbJJ1UouSn1KmEqaSsRKyEsKSxxLV0t4S65MLUwyTLNM_01GTZJNuU3jTipOMk5tTp9Ork8ET1ZPfU_zUDBQQlBHUUdRTFFgUWxRdFHZUeZR-1IpUlNSr1KyUuxTMVM1U1JTpVO7U9RUR1RiVIJUrlS9VP5VS1WFValVrlW1VcZV1VXWVeBWLVZIVkpWY1boVvVW-lcNVylXK1dUV4dXlFeXV8lX2FfhV-JYB1haWGNYdVh3WK5Yr1jlWW1ZvFnzWf5aGlorWlJakVqfWyZboFuvW_RcQFxrXIpc-V1JXWhd8l4TXkVeXV6LXqVewF8EXypfOV8_X2pfmF-wYEFgQ2BlYHNgkWDEYQZhIWFSYeJh62JaYnlilWKsYuxjF2NDY3Bjp2P9ZAlkUmRaZIRknWSjZKpkr2TnZU1lp2XwZlRmnma2Z1hnZ2eAZ5tnoGe9Z_xoWGhlaHRo8mn-agFqBGoeajZqO2pDaoxqk2qVaqVqrGr6axdrrGu3a9lr22wIbAtsRmyMbOdtGW03bTptbG20bj1uaW6XbqpvCG8nbztvV2-Eb55v8nBRcFJwVnC7cU1xeXGFcaFxsHIPcmxyqXLDc2tzbXNwc7N0VXSgdK507XTxdU51nnXLddB1_XYRdit2b3Z_doJ2rHbndvd3B3dTd9d343fld_14DXgZeC94aXh6eK54znjreTl5aHmhefZ6U3p_euZ673sNexR7IHt0e4x7w3vXfA58S3yDfLh8u3zZfOV9GH1bfXV90n3jffV-WX6afq9-sH7HfuB-4n8Cfyt_xn_jf_uAVoCKgKSAroDhgTqBQYGsga-CB4IQgh6CU4JegpuCx4LkgwmDX4O2g72DzIPbg_OD94RIhG-Ed4TEhMWE2YTvhQ6FMoVShWCFbYV7hX2FxYYChjuGYIauhrOGzobRhxOHKYdBh2WHaod2h8uIQIhCiFqIW4iPiO2Ja4nTidiJ4IoGiiKKKIo4iq-Ks4rkivCLT4t6i4yLmYwLjDaMRox2jM-NGY19jX6NgY2Cjb-OPI5kjoqOvo6_jumPGo9Gj0-PYI-Zj6aPwY_6kAqQDZARkBuQM5BVkGyQ1pErkc6SfZKAksGS0JLzkweTH5MnkzqTkJOVk5mTqJP8lFyUb5SHlKCUuJUElQWVIJUulWaVh5XIlcyWMpZslnSWi5cGl3mXhZeVl5eXtJfQl_SYCphvmK2ZK5oTmheaO5phmmqaz5rgmvGbJpstm1ibXZtqm4abjZuhm7Wb7JwynKScvpzEnaqdrp3ZnjyeV56hnsSexZ7NnwGfJ58-n4KfiJ-jn8uf36BCoEOgn6EioS-hpKIAogSiLqJAoqOi2aLqo4qj56Pvo_KkGaQ5pHikwqXEpcumV6Z_po2mmaaspr6m4KbrpwinK6cwpzSnVaeUp5unn6elp9SoB6h9qJqooqknqTSpbqmUqZWp-qrEqvirC6vSrEesZqyXrJisqqyvrTOtSq2NrfGuEq4-rlCus69sr42vm6-nr7ev67ALsHewkrCrsNixBbEwsTaxQrGQsbOyGbJwstyzA7MOsz-0DLQatC-0OLTFtNG01LUEtQi1SLWFtfK2LLaGtoq2pLb6txe3IrcwtzG3Prd1t7a31rfZuJO4yrjQuNm5Hbk-uUO5b7l8uZO7Tbueu-O77byavJ-86r0nvTa9gb2Cvea-Or6Avoq-p768vu6_AL-Xv9XAGsBUwGbAdsCawJzApsC_wOPBAMEEwQfBM8FJwYLBi8GgwaPBtMHFwdXB2MHzwnPCjsLswwnDE8MzwzrDbcQVxFjEgsSixLjE9sUoxVPFisauxtjHysgMyBTII8hbyMzI3MjwyT3JRMlnykrKkMqpytPLvcv1zAbMZsy3zLzNFs2YzerOcM6ozwrPFc8yz3rPfs_dz-nQH9DQ0PXRNtHk0f3SIdMb02_TftP70_zUI9RC1FLUfNSP1S7VddWB1YvVptW51fjWB9ZY1orWvtct137XltfP2AvYJNhN2FTYYNh22L3ZC9kT2VvZX9lh2XzZxtn82jraYtpk2o3audrB2t3bAtsL2xrbT9tV21nbXttu26fb1Nvn3CPcMtw93HPcvd0N3UbdSN1f3YzdqN3j3efelt7l3vjfb9-K35jfsN-y377fv-AS4JXgn-DD4XPhiOHb4e_iLOJD4l7iYeKA4tXi9-NW42rjhOOf5CLkUeSt5LHk6-UZ5Yvlz-Xm5ljmgeaI5wrnD-c651TndOfq6FroZuik6NXo1ukC6Ubp1en-6hjqYuq66wnrFOss62Prjuvk6-7r9ewY7DjsVex07IrssOzL7SDtPO0_7UHtRO2D7dfuDu4V7nrvDu9O71Dveu9874jvj-_r8B_wa_DV8PnxbPGK8azxs_H-8h3yHvIv8kHyRfJa8pfynPLh8wbzCfMR82_zm_Pd9HH0xvTm9On0-PVL9W_2SPZb9qP2rvba9uf2_Pcy9033pve-98H31_iT-KH46_kz-Tf5Y_ll-b35yPnb-d356PoY-oD60vrr-u_68fsJ-4v7qvv1_Ev8ZPzF_TD9YP4J_gr-Hf5J_lT-a_6H_o_-s_66_sj_HP-T_7D_0__eAMECXwMECdkdwiBZJG88S0QlWBdgs2Ded-J7boRTlyGarqI-pAymMqavqHKpSKu6sVvBfMpG0ujWXd2S4FXire6Q7_3y0vd9AAAAAAA=</default>
